services:
  wsgi:
    image: 767397767501.dkr.ecr.us-east-1.amazonaws.com/ata-db-api:latest
    # build: ./backend
    ports:
      - '8000:8000'
    networks:
      - ata-network

  nginx:
    image: 767397767501.dkr.ecr.us-east-1.amazonaws.com/ata-db-frontend:latest
    # build: ./frontend
    ports:
      - '443:443'
    networks:
      - ata-network

networks:
  ata-network:
    driver: bridge

