services:
  flask:
    image: 767397767501.dkr.ecr.us-east-1.amazonaws.com/ata-db-api:latest
    ports:
      - '5000:5000'
    networks:
      - ata-network

  nginx:
    image: 767397767501.dkr.ecr.us-east-1.amazonaws.com/ata-db-frontend:latest
    ports:
      - '443:443'
    networks:
      - ata-network

networks:
  ata-network:
    driver: bridge

