version: 0.2

phases:
  install:
    commands:
      - |
        echo "Install phase entered...";
        echo "Checking if compose.yml has changed...";
        CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD);
        if [[ "$CHANGED_FILES" != *"compose.yml"* ]]; then 
          echo "No compose changes, skipping build."; 
          exit 0; 
        fi
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin "$AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com"
  pre_build:
    commands:
      - echo "Pre-build phase entered..."
  build:
    commands:
      - echo "Build phase entered..."
      - aws ssm put-parameter --name "/ata-db/compose.yml" --type "String" --value "file://compose.yml" --overwrite
  post_build:
    commands:
      - echo "Post-build phase entered..."
artifacts:
  files:
    - '**/*'