AWSTemplateFormatVersion: '2010-09-09'

Description: ATA Flask React app-specific Infrastructure

# Available top-level fields are listed in code completion

# Add Resources Here: uncomment the following lines
Resources:
  AtaDbDeployPipelineArtifactStore:
    Type: AWS::S3::Bucket
    Properties:
      Tag: ata-db-deploy-pipeline

  AtaDbDeployPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore: 
        Location: !Ref AtaDbDeployPipelineArtifactStore
        Type: S3
      Name: ata-db-api-deploy
      PipelineType: V1
      RoleArn: arn:aws:iam::767397767501:role/ata-db-deploy-infrastructure-pipeline
      Tags:
        - ata-db-deploy-pipepline
      Triggers:
        - ProviderType: CodeStarSourceConnection
      Stages:
        Actions:
          - Name: Source
            ActionTypeId:
              Category: Source
              Owner: AWS
              Provider: CodeStarSourceConnection
              Version: '1'
            Configuration:
              ConnectionArn: arn:aws:codeconnections:us-east-1:767397767501:connection/515a1f58-898b-4cd6-95de-b23d42946107
              FullRepositoryId: BYU-TRG-Team/ata-flask-react
              BranchName: main
            OutputArtifacts:
              - Name: SourceArtifact
            RunOrder: 1

          - Name: Deploy
            ActionTypeId:
              Category: Deploy
              Owner: AWS
              Provider: CloudFormation
              Version: '1'
            Configuration:
              ActionMode: CREATE_UPDATE
              StackName: ata-db-codebuild
              RoleArn: arn:aws:iam::767397767501:role/ata-db-deploy-infrastructure-pipeline
              TemplatePath: SourceArtifact::ata-flask-react/pipeline/codebuild/container-build.yml
            InputArtifacts:
              - Name: SourceArtifact
            RunOrder: 2