version: 0.2
phases:
  install:
    runtime-versions: 
      python: 3.9
    commands:
      - echo "Install phase entered..."
      - yum install -y git
  pre_build:
    commands:
      - echo "Pre-build phase entered..."
      - cd $CODEBUILD_SRC_DIR
      - git submodule init
      - git submodule update --recursive
      - pip install -r service/requirements.txt -t service
  build:
    commands:
      - echo "Build phase entered..."
  post_build:
    commands:
      - echo "Post-build phase entered..."
      - docker push $AWS_ECR_REPOSITORY_URI
artifacts:
  base-directory: dist/ata_flask_react
  files:
    - '**/*'