version: 0.2

env:
  secrets-manager:
    DB_HOST:     ATA_DB_CREDENTIALS:host
    DB_USERNAME: ATA_DB_CREDENTIALS:username
    DB_PASSWORD: ATA_DB_CREDENTIALS:password
    DB_PORT:     ATA_DB_CREDENTIALS:port
    DB_NAME:     ata-db-name:ata-db-name

phases:
  install:
    runtime-versions: 
      python: 3.9
    commands:
      - echo "Install phase entered..."
      - echo "ACCOUNT ID is $AWS_ACCOUNT_ID"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin "$AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com"
  pre_build:
    commands:
      - echo "Pre-build phase entered..."
      - pip install -r service/requirements.txt -t service
      - mkdir service/instance
      - cd service/instance
  build:
    commands:
      - echo "Build phase entered..."
      - echo "DB_HOST='$DB_HOST'\n" >> config.py
      - echo "DB_USER='$DB_USERNAME'\n" >> config.py
      - echo "DB_PASSWORD='$DB_PASSWORD'\n" >> config.py
      - echo "DB_PORT='$DB_PORT'\n" >> config.py 
      - echo "DB_NAME='$DB_NAME'\n" >> config.py
      - cd ../..
      - docker build -t $AWS_ECR_REPOSITORY_URI .
  post_build:
    commands:
      - echo "Post-build phase entered..."
      - docker push $AWS_ECR_REPOSITORY_URI
artifacts:
  files:
    - '**/*'