version: 0.2
phases:
  install:
    runtime-versions: 
      python: 3.9
    commands:
      - echo "Install phase entered..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin '$AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com'
  pre_build:
    commands:
      - echo "Pre-build phase entered..."
      - pip install -r service/requirements.txt -t service
  build:
    commands:
      - echo "Build phase entered..."
      - echo "DB_HOST='$DB_HOST'\n" >> config.py
      - echo "DB_USER='$DB_USERNAME'\n" >> config.py
      - echo "DB_PASSWORD='$DB_PASSWORD'\n" >> config.py
      - echo "DB_PORT='$DB_PORT'\n" >> config.py 
      - echo "DB_NAME='$DB_NAME'\n" >> config.py
      - docker build -t $AWS_ECR_REPOSITORY_URI .
  post_build:
    commands:
      - echo "Post-build phase entered..."
      - docker push $AWS_ECR_REPOSITORY_URI
artifacts:
  files:
    - '**/*'