AWSTemplateFormatVersion: '2010-09-09'

Resources:
  # create a VPC for the ECS cluster running a Flask API
  AtaDbDeployVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: project
          Value: ata-db
  
  
  AtaIntenetGateWay:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: project
          Value: ata-db
  
  AtaVPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref AtaDbDeployVPC
      InternetGatewayId: !Ref AtaIntenetGateWay

  AtaPublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref AtaDbDeployVPC
      Tags:
        - Key: project
          Value: ata-db

  AtaPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AtaVPCGatewayAttachment
    Properties:
      RouteTableId: !Ref AtaPublicRouteTable
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: !Ref AtaIntenetGateWay
    
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref AtaDbDeployVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: project
          Value: ata-db

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref AtaDbDeployVPC
      CidrBlock: 10.0.2.0/24
      Tags:
        - Key: project
          Value: ata-db

  AtaPublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref AtaPublicRouteTable

  # AtaNatGatewayAttachment:
  #   Type: AWS::EC2::EIP
  #   DependsOn: AtaVPCGatewayAttachment
  #   Properties:
  #     Domain: vpc
  #     Tags:
  #       - Key: project
  #         Value: ata-db
  
  # AtaNatGateway:
  #   Type: AWS::EC2::NatGateway
  #   Properties:
  #     AllocationId: !GetAtt AtaNatGatewayAttachment.AllocationId
  #     SubnetId: !Ref PublicSubnet
  #     Tags:
  #       - Key: project
  #         Value: ata-db

  # AtaPrivateRouteTable:
  #   Type: AWS::EC2::RouteTable
  #   Properties:
  #     VpcId: !Ref AtaDbDeployVPC
  #     Tags:
  #       - Key: project
  #         Value: ata-db

  # AtaPrivateRoute:
  #   Type: AWS::EC2::Route
  #   Properties:
  #     RouteTableId: !Ref AtaPrivateRouteTable
  #     DestinationCidrBlock: '0.0.0.0/0'
  #     NatGatewayId: !Ref AtaNatGateway
  #     Tags:
  #       - Key: project
  #         Value: ata-db
  
  # AtaPrivateSubnetRouteTableAssociation:
  #   Type: AWS::EC2::SubnetRouteTableAssociation
  #   Properties:
  #     SubnetId: !Ref PrivateSubnet
  #     RouteTableId: !Ref AtaPrivateRouteTable

  AtaDbDeploySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: ata-db-api-ecs-security-group
      GroupDescription: Security group for ATA DB API
      VpcId: !Ref AtaDbDeployVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5000
          ToPort: 5000
          CidrIp: 0.0.0.0/0
      # allow outbound traffic to Postgres in RDS
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 443 
          ToPort: 443 
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 10.0.0.0/16
      Tags:
        - Key: project
          Value: ata-db

  AtaDbDeployPipelineArtifactStore:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: project
          Value: ata-db

  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: ata-db-api
      Tags:
        - Key: project
          Value: ata-db

  CloudWatchLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: ata_db_api_docker_image_logs
      RetentionInDays: 5
      Tags:
        - Key: project
          Value: ata-db

  BuildContainer:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Cache:
        Type: NO_CACHE
      Description: ATA DB API Container Building
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:4.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: AWS_ACCOUNT_ID
            Value: !Ref "AWS::AccountId"
          - Name: AWS_ECR_REPOSITORY_URI
            Value: !Sub ${AWS::AccountId}.dkr.ecr.us-east-1.amazonaws.com/ata-db-api:latest
          - Name: ARTIFACT_FILE
            Value: !Ref ECRRepository
          - Name: RDS_HOST
            Value: '{{resolve:secretsmanager:ATA_DB_CREDENTIALS:SecretString:host}}'
          - Name: DB_NAME
            Value: '{{resolve:secretsmanager:ata-db-name:SecretString:ata-db-name}}'
          - Name: DB_PORT
            Value: '{{resolve:secretsmanager:ATA_DB_CREDENTIALS:SecretString:port}}'
          - Name: DB_USERNAME
            Value: '{{resolve:secretsmanager:ATA_DB_CREDENTIALS:SecretString:username}}'
          - Name: DB_PASSWORD
            Value: '{{resolve:secretsmanager:ATA_DB_CREDENTIALS:SecretString:password}}'
      LogsConfig:
        CloudWatchLogs: 
          GroupName: ata_db_api_docker_image_logs
          Status: ENABLED
      ServiceRole: arn:aws:iam::767397767501:role/service-role/AWSCodePipelineServiceRole-us-east-1-ata-db-api-deploy
      Source:
        BuildSpec: pipeline/buildspecs/build-flask-container.yaml
        GitCloneDepth: 1
        Type: CODEPIPELINE
      Tags:
        - Key: project
          Value: ata-db

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: arn:aws:iam::767397767501:role/service-role/AWSCodePipelineServiceRole-us-east-1-ata-db-api-deploy
      ArtifactStore:
        Type: S3
        Location: !Ref AtaDbDeployPipelineArtifactStore
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: '1'
              Configuration:
                ConnectionArn: arn:aws:codeconnections:us-east-1:767397767501:connection/515a1f58-898b-4cd6-95de-b23d42946107
                FullRepositoryId: BYU-TRG-Team/ata-flask-react
                BranchName: main
              OutputArtifacts:
                - Name: SourceArtifact
        - Name: Build
          Actions:
            - Name: Docker
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref BuildContainer
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildArtifact
              RunOrder: 1
      Tags:
        - Key: project
          Value: ata-db

  CreateCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: ata-db-api
      Tags:
        - Key: project
          Value: ata-db

  CreateTask:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Command: 
          - python -m flask
          Environment:
            - Name: FLASK_APP
              Value: dist/ata_flask_react
          Image: !Sub ${AWS::AccountId}.dkr.ecr.us-east-1.amazonaws.com/${ECRRepository}
          Name: ata-db-api
          PortMappings:
            - ContainerPort: 5000
            - ContainerPort: '{{resolve:secretsmanager:ATA_DB_CREDENTIALS:SecretString:port}}'
      Cpu: 256
      Memory: 512
      ExecutionRoleArn: arn:aws:iam::767397767501:role/ata-db-deploy-infrastructure-pipeline
      NetworkMode: awsvpc
      Tags:
        - Key: project
          Value: ata-db
          
  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref CreateCluster
      DesiredCount: 1  # Number of tasks you want running
      TaskDefinition: !Ref CreateTask
      LaunchType: FARGATE  # Or EC2, depending on your setup
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED  # For public access, optional
          Subnets:
            - !Ref PublicSubnet
          SecurityGroups:
            - !Ref AtaDbDeploySecurityGroup
      Tags:
        - Key: project
          Value: ata-db