AWSTemplateFormatVersion: '2010-09-09'

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      EmptyOnDelete: true
      RepositoryName: ata-db/api
      Tags:
        - Key: project
          Value: ata-db

  CloudWatchLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: ata_db_api_docker_image_logs
      RetentionInDays: 5
      Tags:
        - Key: project
          Value: ata-db


  BuildContainer:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Cache:
        Type: NO_CACHE
      Description: ATA DB API Container Building
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:4.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: AWS_ACCOUNT_ID
            Value: !Ref "AWS::AccountId"
          - Name: AWS_ECR_REPOSITORY_URI
            Value: !Sub ${AWS::AccountId}.dkr.ecr.us-east-1.amazonaws.com/${ECRRepository}}:latest
      LogsConfig:
        CloudWatchLogs: 
          - GroupName: !Ref CloudWatchLogGroup
            Status: ENABLED
            StreamName: ata-db-api-

      ServiceRole: arn:aws:iam::767397767501:role/service-role/AWSCodePipelineServiceRole-us-east-1-ata-db-api-deploy
      Source:
        BuildSpec: pipeline/buildspecs/build-flask-container.yaml
        GitCloneDepth: 1
        Type: CODEPIPELINE
      Tags:
        - Key: project
          Value: ata-db

  CreateCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: ata-db-api
      Tags:
        - Key: project
          Value: ata-db

  CreateTask:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Command: 
          - python -m flask
          Environment:
            - Name: FLASK_APP
              Value: dist/ata_flask_react
          Image: !Ref ECRRepository
          Name: ata-db-api
          PortMappings:
            - ContainerPort: 5000
            - ContainerPort: 5432
      Cpu: 256
      Memory: 512
      ExecutionRoleArn: arn:aws:iam::767397767501:role/ata-db-deploy-infrastructure-pipeline
      NetworkMode: awsvpc
      Tags:
        - Key: project
          Value: ata-db