AWSTemplateFormatVersion: '2010-09-09'

Resources:
  # create a VPC for the ECS cluster running a Flask API
  AtaDbDeployVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: project
          Value: ata-db
  
  
  AtaIntenetGateWay:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: project
          Value: ata-db
  
  AtaVPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref AtaDbDeployVPC
      InternetGatewayId: !Ref AtaIntenetGateWay

  AtaPublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref AtaDbDeployVPC
      Tags:
        - Key: project
          Value: ata-db

  AtaPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AtaVPCGatewayAttachment
    Properties:
      RouteTableId: !Ref AtaPublicRouteTable
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: !Ref AtaIntenetGateWay
    
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref AtaDbDeployVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: project
          Value: ata-db

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref AtaDbDeployVPC
      CidrBlock: 10.0.2.0/24
      Tags:
        - Key: project
          Value: ata-db

  AtaPublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref AtaPublicRouteTable

  # AtaNatGatewayAttachment:
  #   Type: AWS::EC2::EIP
  #   DependsOn: AtaVPCGatewayAttachment
  #   Properties:
  #     Domain: vpc
  #     Tags:
  #       - Key: project
  #         Value: ata-db
  
  # AtaNatGateway:
  #   Type: AWS::EC2::NatGateway
  #   Properties:
  #     AllocationId: !GetAtt AtaNatGatewayAttachment.AllocationId
  #     SubnetId: !Ref PublicSubnet
  #     Tags:
  #       - Key: project
  #         Value: ata-db

  # AtaPrivateRouteTable:
  #   Type: AWS::EC2::RouteTable
  #   Properties:
  #     VpcId: !Ref AtaDbDeployVPC
  #     Tags:
  #       - Key: project
  #         Value: ata-db

  # AtaPrivateRoute:
  #   Type: AWS::EC2::Route
  #   Properties:
  #     RouteTableId: !Ref AtaPrivateRouteTable
  #     DestinationCidrBlock: '0.0.0.0/0'
  #     NatGatewayId: !Ref AtaNatGateway
  #     Tags:
  #       - Key: project
  #         Value: ata-db
  
  # AtaPrivateSubnetRouteTableAssociation:
  #   Type: AWS::EC2::SubnetRouteTableAssociation
  #   Properties:
  #     SubnetId: !Ref PrivateSubnet
  #     RouteTableId: !Ref AtaPrivateRouteTable

  AtaDbDeploySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: ata-db-api-ec2-security-group
      GroupDescription: Security group for ATA DB API EC2 instance
      VpcId: !Ref AtaDbDeployVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443 
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: project
          Value: ata-db

  AtaDbDeployPipelineArtifactStore:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: project
          Value: ata-db

  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: ata-db-api
      Tags:
        - Key: project
          Value: ata-db

  ECRRepositoryFrontend:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: ata-db-frontend
      Tags:
        - Key: project
          Value: ata-db

  ECRAtaDb:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: ata-db
      Tags:
        - Key: project
          Value: ata-db

  CloudWatchLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: ata_db_api_docker_image_logs
      RetentionInDays: 5
      Tags:
        - Key: project
          Value: ata-db

  BuildContainer:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Cache:
        Type: NO_CACHE
      Description: ATA DB API Container Building
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:4.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: AWS_ACCOUNT_ID
            Value: 767397767501
            Type: PLAINTEXT
          - Name: AWS_ECR_REPOSITORY_URI
            Value: 767397767501.dkr.ecr.us-east-1.amazonaws.com/ata-db-api:latest
            Type: PLAINTEXT
          - Name: ARTIFACT_FILE
            Value: !Ref ECRRepository
            Type: PLAINTEXT
      LogsConfig:
        CloudWatchLogs: 
          GroupName: ata_db_api_docker_image_logs
          Status: ENABLED
      ServiceRole: arn:aws:iam::767397767501:role/service-role/AWSCodePipelineServiceRole-us-east-1-ata-db-api-deploy
      Source:
        BuildSpec: pipeline/buildspecs/build-flask-container.yaml
        GitCloneDepth: 1
        Type: CODEPIPELINE
      Tags:
        - Key: project
          Value: ata-db

  FrontendBuildContainer:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Cache:
        Type: NO_CACHE
      Description: ATA DB Frontend Container Building
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:4.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: AWS_ACCOUNT_ID
            Value: 767397767501
            Type: PLAINTEXT
          - Name: AWS_ECR_REPOSITORY_URI
            Value: 767397767501.dkr.ecr.us-east-1.amazonaws.com/ata-db-frontend:latest
            Type: PLAINTEXT
          - Name: ARTIFACT_FILE
            Value: !Ref ECRRepositoryFrontend
            Type: PLAINTEXT
      LogsConfig:
        CloudWatchLogs: 
          GroupName: ata_db_api_docker_image_logs
          Status: ENABLED
      ServiceRole: arn:aws:iam::767397767501:role/service-role/AWSCodePipelineServiceRole-us-east-1-ata-db-api-deploy
      Source:
        BuildSpec: pipeline/buildspecs/build-react-container.yaml
        GitCloneDepth: 1
        Type: CODEPIPELINE
      Tags:
        - Key: project
          Value: ata-db

  AtaDbBuildContainer:
    Type: AWS::CodeBuild::Project
    DependsOn: 
      - FrontendBuildContainer
      - BuildContainer
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Cache:
        Type: NO_CACHE
      Description: ATA DB API Container Building
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:4.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: AWS_ACCOUNT_ID
            Value: 767397767501
            Type: PLAINTEXT
          - Name: AWS_ECR_REPOSITORY_URI
            Value: 767397767501.dkr.ecr.us-east-1.amazonaws.com/ata-db:latest
            Type: PLAINTEXT
          - Name: ARTIFACT_FILE
            Value: !Ref ECRAtaDb
            Type: PLAINTEXT
      LogsConfig:
        CloudWatchLogs: 
          GroupName: ata_db_api_docker_image_logs
          Status: ENABLED
      ServiceRole: arn:aws:iam::767397767501:role/service-role/AWSCodePipelineServiceRole-us-east-1-ata-db-api-deploy
      Source:
        BuildSpec: pipeline/buildspecs/build-flask-container.yaml
        GitCloneDepth: 1
        Type: CODEPIPELINE
      Tags:
        - Key: project
          Value: ata-db

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: ata-db-api-pipeline
      RoleArn: arn:aws:iam::767397767501:role/service-role/AWSCodePipelineServiceRole-us-east-1-ata-db-api-deploy
      ArtifactStore:
        Type: S3
        Location: !Ref AtaDbDeployPipelineArtifactStore
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: '1'
              Configuration:
                ConnectionArn: arn:aws:codeconnections:us-east-1:767397767501:connection/515a1f58-898b-4cd6-95de-b23d42946107
                FullRepositoryId: BYU-TRG-Team/ata-flask-react
                BranchName: main
              OutputArtifacts:
                - Name: SourceArtifact
        - Name: Build
          Actions:
            - Name: Docker
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref BuildContainer
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildArtifact
              RunOrder: 1
        - Name: BuildFrontend
          Actions:
            - Name: Docker
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref FrontendBuildContainer
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: FrontendBuildArtifact
              RunOrder: 1
        - Name: BuildAtaDb
          Actions:
            - Name: Docker
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref AtaDbBuildContainer
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: AtaDbBuildArtifact
              RunOrder: 1
      Tags:
        - Key: project
          Value: ata-db

  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: EC2InstancePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:Describe*
                  - ec2:AttachVolume
                  - ec2:DetachVolume
                  - ec2:StartInstances
                  - ec2:StopInstances
                  - ec2:TerminateInstances
                Resource: '*'
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: arn:aws:s3:::ata-db-deploy-pipeline-artifact-store/*
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                Resource: '*'

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    DependsOn: EC2InstanceRole
    Properties:
     Roles:
        - !Ref EC2InstanceRole

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroupIds:
      - !Ref AtaDbDeploySecurityGroup
      SubnetId: !Ref PublicSubnet
      ImageId: ami-04681163a08179f28 # Amazon Linux 2 AMI (HVM), SSD Volume Type
      IamInstanceProfile: !Ref EC2InstanceProfile
      KeyName: ata-db-api
      Tags:
      - Key: project
        Value: ata-db
      - Key: Name
        Value: ata-db-api
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum install -y awslogs
          cat <<EOF >> /etc/awslogs/awslogs.conf
          [general]
          state_file = /var/lib/awslogs/agent-state

          [/var/log/messages]
          file = /var/log/messages
          log_group_name = ata_db_api_docker_image_logs
          log_stream_name = {instance_id}/var/log/messages
          datetime_format = %b %d %H:%M:%S

          [/var/log/docker]
          file = /var/log/docker
          log_group_name = ata_db_api_docker_image_logs
          log_stream_name = {instance_id}/var/log/docker
          datetime_format = %Y-%m-%dT%H:%M:%S.%f
          EOF

          service awslogs start
          chkconfig awslogs on
          yum update -y
          yum install -y python3 git
          yum install -y docker
          service docker start
          usermod -a -G docker ec2-user
          chkconfig docker on
          $(aws ecr get-login --no-include-email --region us-east-1)
          docker pull 767397767501.dkr.ecr.us-east-1.amazonaws.com/ata-db:latest
          docker run -d -p 80:80 -p 443:443 767397767501.dkr.ecr.us-east-1.amazonaws.com/ata-db:latest

Outputs:
  EC2InstancePublicIP:
    Description: Public IP address of the EC2 instance
    Value: !GetAtt EC2Instance.PublicIp